# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Maintain dependencies for frontend (npm, Angular LTS)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
      time: "09:00"
      # Use America Standard Time (PDT)
      timezone: "America/Tijuana"
    # Raise pull requests for version updates to npm against the `stable` branch
    target-branch: "stable"
    # Max number of PRs allowed
    open-pull-requests-limit: 10
    ignore:
      # Ignore updates outside of ^17.0.x for Angular packages
      - dependency-name: "@angular/*"
        # Limit updates to versions within ^17.0 [LTS ends 2025-05-15]
        versions: [ "<17.0.0", ">=18.0.0" ]

  # Maintain dependencies for backend, ignoring typescript updates (uses specific version ">=4.9.3 and <5.2.0")
  - package-ecosystem: "npm"`
    directory: "/backend"
    schedule:
      interval: "daily"
      time: "09:00"
      # Use America Standard Time (PDT)
      timezone: "America/Tijuana"
    # Raise pull requests for version updates to npm against the `stable` branch
    target-branch: "stable"
    # Max number of PRs allowed
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "typescript"
        versions: ">=4.9.3 <5.2.0"

